### PR TITLE
Add a method of accessing the storage cells

### PR DESCRIPTION
**Pull request by Amaz1**
Here you go, I think that I've updated everything to match the rewrite!
*N.B. I forgot to mention this, but this requires the latest dev version to work correctly, because it uses the new key value itemstack metadata (https://github.com/minetest/minetest/commit/f2aa2c6a986dec47856c49ae5f54fbf3c688e027)*

### CODE REVIEW

**Comment by octacian** [comment]
Thanks for submitting. I just completed the textures for the ME chest and was thinking that I'll probably implement this manually (with mention of your username ofc) as it wouldn't make sense to just commit the textures themselves.

~Oh, and for the time being, I'm going to modify it slightly to not use the new key value itemstack meta as many players do not use the dev version, especially Windows users.~ NVM, will use. Might be annoying for some, but it makes dev so much easier.

**Comment by Desour** [comment]
Ahh, ignore that non dev version user, they shouldn't hinder you.
They can update their version when the new Minetest version comes out.

**Comment by octacian** [comment]
@DS-minetest: Yes, that is true. If they really want to use it they can update to dev, it would only take a few minutes anyway.

**Comment by octacian** [comment]
Merged with slight modifications. It is now called an ME Chest rather than ME Cell Access. I've also made my own texture for it rather than reusing the texture from AE2.

888367b4f6ad542b2f272fac00ad105d38aed71c

Thanks for your work on this @Amaz1! I'll be working on textures for more ME drives soon.

**Comment by Amaz1** [comment]
No problem, glad that it helped!
Do you think that the drive capacity should refer to max number of items a drive can hold, or the max number of stacks? With some metadata manipulation, it *should* be possible to limit the number of items to the max (e.g. 4000). The inventory would probably need to be kept 4000 slots big, so that 4000 tools/unstackable things could be put in there...

**Comment by octacian** [comment]
Sorry, haven't been able to get back to this yet.

Yes, I noticed there are some major issues in the capacity system. I personally see two solutions
* Limit by number of items (default max of 8k, yeah, I plan on changing it - 4k is only ~900 items more than default chests)
* or Limit by number of stacks

Personally, I think we should limit the number of items as one can then be very exact, whereas the math could get a bit weird limiting the number of stacks. The final issue related to this is the number of slots on the final page. Sometimes there might be fewer slots needed on the final page due to the drive capacity. The only solution that I know of is to introduce another inventory with a smaller number of slots.

Anyways, further input on this would be greatly appreciated.

**Pull request closed without merging**
